version: "3.9"
services:
  odoo-web:
    container_name: ${AP_DK_CON_ODOO}
    image: odoo:16.0
    depends_on:
      - odoo-pg
    ports:
      - "${AP_PORT_GITLAB_PUBLIC}:8069"
    environment:
      - HOST=odoo-pg
      - USER=odoo
      - PASSWORD=myodoo
      - PASSWORD_FILE=/run/secrets/postgresql_password
    restart: always
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    secrets:
      - postgresql_password

secrets:
  postgresql_password:
    file: odoo_pg_pass
