# https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
version: "3.9"

services:
    pga:
        container_name: pga
        image: dpage/pgadmin4
        # build:
        #     context: ./
        #     args:
        #         VERSION: latest
        #     dockerfile: ./dockerfiles/pga.Dockerfile
        environment:
            # pgAdmin runs as the pgadmin user (UID: 5050) in the pgadmin group (GID: 5050) in the container.
            PGADMIN_DEFAULT_EMAIL: "scripto@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "${AP_SECRET_PGA_PASS}"
            # PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pga_pass # will not work 100% with Docker Compose, use Docker Swarm instead
            PGADMIN_LISTEN_PORT: 443
            PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
            # PGADMIN_CONFIG_LOGIN_BANNER: 'Authorised users only!'
            PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
            # PGADMIN_SERVER_JSON_FILE: # Default: /pgadmin4/servers.json
            # GUNICORN_ACCESS_LOGFILE: /pgadmin/logs/access.log

            # Reverse proxy
            # Number of values to trust for X-Forwarded-For
            # PROXY_X_FOR_COUNT = 1
            # Number of values to trust for X-Forwarded-Proto.
            # PROXY_X_PROTO_COUNT = 0
            # Number of values to trust for X-Forwarded-Host.
            # PROXY_X_HOST_COUNT = 0
            # Number of values to trust for X-Forwarded-Port.
            # PROXY_X_PORT_COUNT = 1
            # Number of values to trust for X-Forwarded-Prefix.
            # PROXY_X_PREFIX_COUNT = 0
        healthcheck:
            test: curl --fail -I ${AP_URL_PGA} || exit 1
            interval: 15s
            timeout: 5s
            retries: 5
        restart: always
        tty: true
        ports:
            - ${AP_PORT_PGA_PUBLIC}:443
        volumes:
            - ${AP_SERVER_PGA_DATA_DIR}:/var/lib/pgadmin
            # - ./configs/pga/servers.json:/pgadmin4/servers.json
            - ${AP_NC_DIR}/ws/sql:/var/lib/pgadmin/storage/pnphuong29_gmail.com
            # - ./entrypoints/ap_entrypoint_${AP_DK_CON_PGA}.sh:/ap_entrypoint.sh:ro
        # entrypoint: /ap_entrypoint.sh
        # entrypoint: ['sh']
        # secrets:
        # - pga_pass
