version: "3.9"
services:
    orangehrm:
        container_name: ${AP_DK_CON_ORANGEHRM}
        image: orangehrm/orangehrm
        restart: always
        tty: true
        ports:
            - ${AP_PORT_ORANGEHRM_PUBLIC}:80
        # volumes:
        #     - ${AP_SERVER_OPENPROJECT_DATA_DIR}/assets:/var/openproject/assets
        #     - ${AP_SERVER_OPENPROJECT_DB_DIR}/pg:/var/openproject/pgdata
