# https://hub.docker.com/r/mtlynch/picoshare/
version: "3.9"

services:
    picoshare:
        container_name: ${AP_DK_CON_PICOSHARE}
        image: mtlynch/picoshare
        environment:
            - PORT=${AP_PORT_PICOSHARE_PUBLIC}
            - PS_SHARED_SECRET=${AP_SECRET_PICOSHARE}
            - PS_BEHIND_PROXY=true
        ports:
            - ${AP_PORT_PICOSHARE_PUBLIC}:${AP_PORT_PICOSHARE_PUBLIC}
        restart: always
        tty: true
        command: -db /data/store.db
        volumes:
            - ${AP_SERVER_PICOSHARE_DATA_DIR}:/data
