# https://hub.docker.com/r/sigoden/dufs
version: "3.9"

services:
    dufs:
        container_name: dufs
        # image: sigoden/dufs
        build:
            context: .
            args:
                VERSION: latest
            dockerfile: ./dockerfiles/dufs.Dockerfile
        restart: always
        tty: true
        ports:
            - ${AP_PORT_DUFS_PUBLIC}:5000
        volumes:
            - "${HOME}/.cargo/bin/dufs:/bin/dufs"
            - "${AP_DATA1_DIR}/dufs/data:/data"
            - ./entrypoints/ap_entrypoint_dufs.sh:/ap_entrypoint.sh:ro
        entrypoint: "dufs -p 5000 -a albert:${AP_SECRET_DUFS_USER_ALBERT_PASS}@/:rw -A /data"
        # entrypoint: /ap_entrypoint.sh
