Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu-server-22-jammy-amd64-mattermost'
  # config.vm.box = 'ubuntu-server-22-jammy-amd64'
  config.vm.box_url = "file://#{ENV['AP_SERVER_DATA1_DIR']}/file-server-secure/vms/vagrant/vagrant_ubuntu_server_22_jammy_amd64.box"

  config.vm.provider 'virtualbox' do |vb|
    vb.name = ENV['AP_VG_VM_MATTERMOST_NAME']
    vb.check_guest_additions = true
    vb.cpus = 8
    vb.memory = 8192
  end

  config.ssh.private_key_path = ENV['AP_VG_KEY_PRIVATE_PATH']
  config.vm.network 'forwarded_port', host: ENV['AP_PORT_MATTERMOST'], guest: ENV['AP_PORT_MATTERMOST'], protocol: 'tcp'
  config.vm.synced_folder ENV['AP_MATTERMOST_SERVER_DATA_DIR'], ENV['AP_MATTERMOST_SERVER_DATA_DIR'],
                          SharedFoldersEnableSymlinksCreate: false
  # SharedFoldersEnableSymlinksCreate: false, owner: 'www-data', group: 'www-data'
end
