Vagrant.configure("2") do |config|
  config.vm.box = "official-centos-stream-8-x86-64"
  config.vm.box_url = "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-Vagrant-8-20201217.0.x86_64.vagrant-virtualbox.box"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-official-centos-stream-8-x86-64"
  end
end
