Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu-server-22-jammy-amd64-sofea'
  config.vm.box_url = "file://#{ENV['AP_SERVER_DATA1_DIR']}/file-server-secure/vms/vagrant/vagrant_ubuntu_server_22_jammy_amd64.box"

  config.vm.provider 'virtualbox' do |vb|
    vb.name = ENV['AP_VG_VM_SOFEA']
    vb.check_guest_additions = true
    vb.cpus = 4
    vb.memory = 4096
  end

  config.ssh.private_key_path = ENV['AP_VG_KEY_PRIVATE_PATH']
  # config.vm.network 'public_network', bridge: 'eno2: LAN2', ip: '192.168.1.128'
  config.vm.network 'forwarded_port', host: 8023, guest: 8023, protocol: 'tcp'
  config.ssh.port = 8023
  # config.ssh.guest_port = 2223
  config.ssh.keep_alive = true

  # config.vm.synced_folder ENV['AP_JOPLIN_WEBDAV_DATA_DIR'], ENV['AP_JOPLIN_WEBDAV_DATA_DIR'],
  # SharedFoldersEnableSymlinksCreate: false, owner: 'www-data', group: 'www-data'
end
