Vagrant.configure("2") do |config|
  config.vm.box = "official-fedora-33"
  config.vm.box_url = "https://nrt.edge.kernel.org/fedora-buffet/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-official-fedora-33"
  end
end
