Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu-server-22-jammy-amd64-gitlab'
  # config.vm.box_url = "file://#{ENV['AP_DATA1_DIR']}/vms/vm-images/vagrant/vagrant_nextcloud.box"
  config.vm.box_url = "file://#{ENV['AP_DATA1_DIR']}/vms/vm-images/vagrant/vagrant_ubuntu_server_22_jammy_amd64.box"

  config.vm.provider 'virtualbox' do |vb|
    vb.name = ENV['AP_VG_VM_GITLAB_NAME']
    vb.check_guest_additions = true
    vb.cpus = 4
    vb.memory = 4096
  end

  config.ssh.private_key_path = ENV['AP_VG_KEY_PRIVATE_PATH']
  config.vm.network 'forwarded_port', host: ENV['AP_PORT_GITLAB'], guest: ENV['AP_PORT_GITLAB'], protocol: 'tcp'
  config.vm.network 'forwarded_port', host: ENV['AP_PORT_GITLAB_HTTPS'], guest: ENV['AP_PORT_GITLAB_HTTPS'],
                                      protocol: 'tcp'

  config.vm.synced_folder "#{ENV['AP_GITLAB_SERVER_DATA_DIR']}", "#{ENV['AP_GITLAB_SERVER_DATA_DIR']}",
                          SharedFoldersEnableSymlinksCreate: false, owner: 'www-data', group: 'www-data'
  config.vm.synced_folder "#{ENV['AP_PRJ_SSL7_DIR']}/letsencrypt", '/letsencrypt',
                          SharedFoldersEnableSymlinksCreate: false
  # SharedFoldersEnableSymlinksCreate: false, owner: 'mysql', group: 'mysql'
  config.vm.synced_folder ENV['AP_PRJ_NC7_DIR'], ENV['AP_GITLAB_SERVER_DOCUMENT_ROOT'],
                          SharedFoldersEnableSymlinksCreate: false, owner: 'www-data', group: 'www-data'
end
