Vagrant.configure('2') do |config|
  config.vm.box = 'pnphuong29/centos-stream-8-x86-64'
  config.vm.box_version = '1.0.0'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = ENV['AP_VG_VM_C1_NAME']
    vb.check_guest_additions = true
    vb.cpus = 2
    vb.memory = 1024
  end

  config.vm.synced_folder ENV['AP_SHARES_LOCAL_DIR'], ENV['AP_VG_GUEST_SHARES_LOCAL_DIR'], SharedFoldersEnableSymlinksCreate: false,
                          owner: 'vagrant', group: 'vagrant',
                          mount_options: ['rw', 'uid=1000', 'gid=1000']

  config.vm.synced_folder ENV['AP_PRJ_VMS28_DIR'], ENV['AP_VG_GUEST_PRJ_VMS28_DIR'], SharedFoldersEnableSymlinksCreate: false,
                          owner: 'vagrant', group: 'vagrant',
                          mount_options: ['ro', 'uid=1000', 'gid=1000']

  config.vm.synced_folder ENV['AP_PRJ_PUB7_DIR'], ENV['AP_VG_GUEST_PRJ_PUB7_DIR'], SharedFoldersEnableSymlinksCreate: false,
                          owner: 'vagrant', group: 'vagrant',
                          mount_options: ['ro', 'uid=1000', 'gid=1000']

  config.vm.provision 'shell',
                      run: 'always',
                      inline: 'sudo chown -R vagrant /home/vagrant/pnphuong29'
end
