<?php
$CONFIG = array (
	'default_language' => 'en',
	// 'force_language' => 'en',
	'default_locale' => 'en_US',
	// 'force_locale' => 'en_US',
	'default_phone_region' => 'VN',
	'defaultapp' => 'dashboard,files',
	'knowledgebaseenabled' => true,
	'allow_user_to_change_display_name' => true,
	'remember_login_cookie_lifetime' => 60*60*24*15,
	'session_lifetime' => 60 * 60 * 24,
	'session_keepalive' => true,
	'auto_logout' => false,
	'token_auth_enforced' => true,
	'token_auth_activity_update' => 60,
	'auth.bruteforce.protection.enabled' => true,
	'auth.webauthn.enabled' => true,
	'auth.storeCryptedPassword' => true,
	// 'logo_url' => 'https://example.org',
	// 'lost_password_link' => 'https://example.org/link/to/password/reset',
	'trashbin_retention_obligation' => 'auto',
	'versions_retention_obligation' => 'auto',
	'config_is_read_only' => false,

	'enable_previews' => true,
	'preview_max_x' => 4096,
	'preview_max_x' => 4096,
	'preview_max_filesize_image' => 50,
	'preview_max_memory' => 128,
	// 'preview_imaginary_url' => 'http://previews_hpb:8088/',
	// 'enabledPreviewProviders' => [
        // 'OC\Preview\PNG',
        // 'OC\Preview\JPEG',
        // 'OC\Preview\GIF',
        // 'OC\Preview\BMP',
        // 'OC\Preview\XBitmap',
        // 'OC\Preview\MP3',
        // 'OC\Preview\TXT',
        // 'OC\Preview\MarkDown',
        // 'OC\Preview\OpenDocument',
        // 'OC\Preview\Krita',
	// ],

	'memcache.local' => '\OC\Memcache\APCu',
	// 'memcache.distributed' => '\OC\Memcache\Memcached',
	'memcache.distributed' => '\OC\Memcache\Redis',
	'filelocking.enabled' => true,
	'memcache.locking' => '\OC\Memcache\Redis',

	// socket connection is recommended if Redis is running on the same system as Nextcloud
	'redis' => [
    	'host' => '/var/run/redis/redis.sock',
    	// 'host' => 'localhost',
		'port' => 0,
		// 'port' => 6379,
		// 'password' => '',
		'dbindex' => 0,
		'timeout' => 0.0,
	],
);
