<?php
$CONFIG = array(
	'instanceid' => 'oc7pu38oa37r',
	'passwordsalt' => 'DiwdgO/vW9TlV8KNRWY5MNmDHNA+kI',
	'secret' => 'z0b+fulZQQiaIxpz2M2dYHKOeHOCiOpIDUhMe9hCViBOLjcm',
	'trusted_domains' =>
	array(
		0 => 'localhost',
		1 => 'ohmmanipadmehum.ddns.info',
	),
	'datadirectory' => '/mnt/lvm/data1/nextcloud/data',
	'dbtype' => 'mysql',
	'version' => '25.0.0.18',
	'overwrite.cli.url' => 'https://ohmmanipadmehum.ddns.info:8443/',
	'dbname' => 'nextcloud',
	'dbhost' => 'localhost',
	'dbport' => '',
	'dbtableprefix' => 'oc_',
	'mysql.utf8mb4' => true,
	'dbuser' => 'nextcloud',
	'dbpassword' => '7f1f90643d111e17f',
	'installed' => true,
	'htaccess.RewriteBase' => '/',
	'maintenance' => false,
	'default_language' => 'en',
	'default_locale' => 'en_US',
	'default_phone_region' => 'VN',
	'defaultapp' => 'dashboard,files',
	'knowledgebaseenabled' => true,
	'allow_user_to_change_display_name' => true,
	'remember_login_cookie_lifetime' => 1296000,
	'session_lifetime' => 86400,
	'session_keepalive' => true,
	'auto_logout' => false,
	'token_auth_enforced' => true,
	'token_auth_activity_update' => 60,
	'auth.bruteforce.protection.enabled' => true,
	'auth.webauthn.enabled' => true,
	'auth.storeCryptedPassword' => true,
	'trashbin_retention_obligation' => 'auto',
	'versions_retention_obligation' => 'auto',
	'config_is_read_only' => false,
	'enable_previews' => true,
	'preview_max_x' => 4096,
	'preview_max_filesize_image' => 50,
	'preview_max_memory' => 128,
	'memcache.local' => '\\OC\\Memcache\\APCu',
	'memcache.distributed' => '\\OC\\Memcache\\Redis',
	'filelocking.enabled' => true,
	'memcache.locking' => '\\OC\\Memcache\\Redis',
	'redis' =>
	array(
		'host' => '/var/run/redis/redis.sock',
		'port' => 0,
		'dbindex' => 0,
		'timeout' => 0.0,
	),
	'updater.secret' => '$2y$10$.CgdhdAItHPIFiGM8IYRd.Ptr1j2keTHAaSzcXCuLRqr0Cl6.oHni',
);
