Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/8"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-official-oracle-linux-8"
  end
end
