# https://docs.docker.com/engine/reference/builder/

FROM nginx:1.21.6

# COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# COPY ./conf/conf.d/default.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT [ "bash" ]
