# Z commands
alias zdl="cd \${AP_DL_DIR}"
alias zsymlinks="cd \${AP_SYMLINKS_DIR}"
alias zsoft="cd \${AP_SOFT_DIR}"
alias zsoftbin="cd \${AP_SOFT_DIR}/bin"
alias zconfigs="cd \${AP_CONFIGS_DIR}"
alias zcache="cd \${AP_CACHE_DIR}"
alias zman="cd \${AP_MAN_DIR}"
alias zcompletions="cd \${AP_COMPLETIONS_DIR}"
alias ztmp="cd \${AP_TMP_DIR}"
alias zlogs="cd \${AP_LOGS_DIR}"
alias zprj="cd \${AP_PRJ_DIR}"

alias zst="cd \${HOME}/scripto"
alias zsc="cd \${HOME}/scripto-common"
alias zsm="cd \${HOME}/scripto-main"
alias zsr="cd \${HOME}/scripto-share"
alias zsdata="cd \${HOME}/scripto-data"

alias zdata="cd \${AP_DATA_DIR}"
alias zwww="cd \${AP_WWW_DIR}"
alias zwww2="cd \${AP_WWW_DIR}/www"
alias zwwwtest="cd \${AP_WWW_DIR}/test"
alias zwwwtmp="cd \${AP_WWW_DIR}/tmp"

alias zetc="cd /etc"
alias zvar="cd /var"
alias zvarlog="cd /var/log"

# Z commands - Linux
alias zlocalshare="cd \${HOME}/.local/share"
alias zlocalstate="cd \${HOME}/.local/state"
alias zdesktopshortcuts="cd \${HOME}/.local/share/applications"
alias zconfig="cd \${HOME}/.config"
alias zautostart="cd \${HOME}/.config/autostart"
alias zusersnap="cd \${HOME}/snap"
alias zsnap="cd /snap"
alias zsnapdesktopshortcuts="cd /var/lib/snapd/desktop/applications"
