# https://misc.flogisoft.com/bash/tip_colors_and_formatting

# Escape strings
export AP_ESCAPE_DEFAULT='\e[' # Use for 8/16 colors
# export AP_ESCAPE_DEFAULT='\033['                         # Use for 8/16 colors
export AP_ESCAPE_EXTENDED_FG="${AP_ESCAPE_DEFAULT}38;5;" # Use for 88/256 foreground colors
export AP_ESCAPE_EXTENDED_BG="${AP_ESCAPE_DEFAULT}48;5;" # Use for 88/256 background colors
export AP_ESCAPE_RESET_ALL="${AP_ESCAPE_DEFAULT}0m"

# Foreground colors
export AP_COLOR_FG_DEFAULT=39

export AP_COLOR_FG_RED=31
export AP_COLOR_FG_GREEN=32
export AP_COLOR_FG_YELLOW=33
export AP_COLOR_FG_MAGENTA=35
export AP_COLOR_FG_CYAN=36

export AP_COLOR_FG_LIGHT_RED=91
export AP_COLOR_FG_LIGHT_GREEN=92
export AP_COLOR_FG_LIGHT_YELLOW=93
export AP_COLOR_FG_LIGHT_MAGENTA=95
export AP_COLOR_FG_LIGHT_CYAN=96

# Background colors
export AP_COLOR_BG_DEFAULT=49

export AP_COLOR_BG_RED=41
export AP_COLOR_BG_GREEN=42
export AP_COLOR_BG_YELLOW=43
export AP_COLOR_BG_MAGENTA=45
export AP_COLOR_BG_CYAN=46

export AP_COLOR_BG_LIGHT_RED=101
export AP_COLOR_BG_LIGHT_GREEN=102
export AP_COLOR_BG_LIGHT_YELLOW=103
export AP_COLOR_BG_LIGHT_MAGENTA=105
export AP_COLOR_BG_LIGHT_CYAN=106

# Formatting
export AP_FORMAT_DEFAULT=21

export AP_FORMAT_BOLD_SET=1
export AP_FORMAT_DIM_SET=2
export AP_FORMAT_UNDERLINE_SET=4
export AP_FORMAT_BLINK_SET=5
export AP_FORMAT_HIDDEN_SET=8

export AP_FORMAT_BOLD_UNSET=21
export AP_FORMAT_DIM_UNSET=22
export AP_FORMAT_UNDERLINE_UNSET=24
export AP_FORMAT_BLINK_UNSET=25
export AP_FORMAT_HIDDEN_UNSET=28

# Samples
export AP_SCHEME_COLOR_DEFAULT="${AP_COLOR_FG_DEFAULT};${AP_COLOR_BG_DEFAULT};${AP_FORMAT_BOLD_SET}"
export AP_SCHEME_COLOR_RED="${AP_COLOR_FG_RED};${AP_COLOR_BG_DEFAULT};${AP_FORMAT_BOLD_SET}"
export AP_SCHEME_COLOR_GREEN="${AP_COLOR_FG_GREEN};${AP_COLOR_BG_DEFAULT};${AP_FORMAT_BOLD_SET}"
export AP_SCHEME_COLOR_CYAN="${AP_COLOR_FG_CYAN};${AP_COLOR_BG_DEFAULT};${AP_FORMAT_BOLD_SET}"
export AP_SCHEME_COLOR_MAGENTA="${AP_COLOR_FG_MAGENTA};${AP_COLOR_BG_DEFAULT};${AP_FORMAT_BOLD_SET}"
export AP_SCHEME_COLOR_YELLOW="${AP_COLOR_FG_YELLOW};${AP_COLOR_BG_DEFAULT};${AP_FORMAT_BOLD_SET}"
export AP_SCHEME_COLOR_LIGHT_YELLOW="${AP_COLOR_FG_LIGHT_YELLOW};${AP_COLOR_BG_DEFAULT};${AP_FORMAT_BOLD_SET}"
