Vagrant.configure('2') do |config|
  config.vm.box = 'pnphuong29/ubuntu-server-focal-amd64'
  config.vm.box_version = '1.0.0'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = ENV['AP_VG_VM_U3_NAME']
    vb.check_guest_additions = true
    vb.cpus = 1
    vb.memory = 512
  end
end
