Vagrant.configure("2") do |config|
  config.vm.box = "official-centos-7-x86-64"
  config.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-official-centos-7-x86-64"
  end
end
